---
title: "Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(RSQLite)
```

```{r}

con = dbConnect(RSQLite::SQLite(), dbname="/Users/paul2/Desktop/cs0320/term-project-as300-dthuku-jryoo-ptouma-sbelete/java code/data/preprocess/main.sqlite3")


system("ls *.db", show=TRUE)
sqlite    <- dbDriver("SQLite")
exampledb <- dbConnect(sqlite,"/Users/paul2/Desktop/cs0320/term-project-as300-dthuku-jryoo-ptouma-sbelete/java code/data/preprocess/main.sqlite3")
dbListTables(exampledb)
dbGetQuery(exampledb, "SELECT * FROM main")
results <- dbSendQuery(exampledb, "SELECT * FROM main")
data = fetch(results,-1)
data = data[ , 2:15]
data$real = as.factor(data$real)
data$real = make.names(data$real)
data$c1l1 = as.factor(data$c1l1)
data$c1l2 = as.factor(data$c1l2)
data$c1l3 = as.factor(data$c1l3)
control <- trainControl(method="cv", number=10, classProbs=TRUE, summaryFunction=twoClassSummary)
model = train(real ~ ., data=data, method = 'glm', metric="ROC", trControl=control,na.action = na.pass)
model
saveRDS(model, "model.rds")

```